import {
    AudioPostRecordSchema,
    type AudioPostRecord,
    type AudioPostView,
    type AudioEmbed,
    type AudioEmbedView,
    type ReplyRef,
    type TranscriptEnrichmentRecord,
} from 'shared/types/audio';
import type { ProfileViewBasic } from 'shared/types/views';
import type {
    AudioPostDependencies,
    AudioPostQueryOptions,
    AudioPostThreadOptions,
} from '../ports/audio-posts-dependencies';
import { NSID } from 'shared/nsid';

/**
 * AudioPostService — CRUD + batched hydration for the Antiphony canonical
 * `dev.antiphony.audio.post` model (Stream 1 PR2). Self-contained and fully
 * additive: it does NOT touch the legacy `PromptService`/`HydrationService`,
 * so Vox Pop keeps running on the old `/prompts` + `/replies` surface while
 * the new `/posts` surface is validated on its own.
 *
 * Three model rules this service enforces (see `specs/antiphony-data-model.md`):
 *  1. `kind` is derived from `reply` presence at write time (cheap index).
 *  2. The transcript is platform enrichment, **lifted into the embed view at
 *     read time** — never stored on the canonical record.
 *  3. The stored audio is a canonical storage URL (`BlobRef.ref`); the view
 *     carries a short-lived signed playback URL.
 */

export interface CreateAudioPostInput {
    /** Multi-tenant isolation key — the origin app creating the post. */
    originAppId: string;
    /** Authoring user id. */
    authorId: string;
    /** Optional AT Protocol identity of the author. */
    authorDid?: string;
    /** Optional org context. */
    orgId?: string | null;
    /** User-authored text. May be empty for pure-audio posts. */
    text: string;
    /** Optional headline (prompt feature only). */
    title?: string;
    /** The uploaded audio attachment. */
    embed?: AudioEmbed;
    /** Present ⇒ this post is a reply (StrongRef root + parent). */
    reply?: ReplyRef;
    /** BCP-47 language tags. */
    langs?: string[];
    /** Author self-label values. */
    selfLabels?: string[];
}

/**
 * Build the canonical `at://` uri for a post. v1 uses the author's DID when
 * present, else the internal author id, so the uri is deterministic AND
 * parseable back to the post id (last path segment). Federation later swaps
 * this for the real repo uri without changing the call sites.
 *
 * Exported so the threading query and the StrongRefs handed to clients are
 * generated by the same rule.
 */
export function buildPostUri(record: Pick<AudioPostRecord, 'id' | 'authorId' | 'authorDid'>): string {
    const authority = record.authorDid ?? record.authorId;
    return `at://${authority}/${NSID.AudioPost}/${record.id}`;
}

export class AudioPostService {
    constructor(private readonly deps: AudioPostDependencies) {}

    /**
     * Create a canonical post. Derives `kind` from `reply` presence and drops
     * `title` on replies (the record invariant forbids it). The record is
     * schema-validated before it's persisted.
     */
    async createPost(input: CreateAudioPostInput): Promise<AudioPostRecord> {
        const kind: AudioPostRecord['kind'] = input.reply ? 'reply' : 'prompt';

        const record = AudioPostRecordSchema.parse({
            id: this.deps.newPostId(),
            originAppId: input.originAppId,
            authorId: input.authorId,
            authorDid: input.authorDid,
            orgId: input.orgId ?? undefined,
            kind,
            text: input.text,
            // Replies carry no title (record invariant); only prompts do.
            title: kind === 'prompt' ? input.title : undefined,
            embed: input.embed,
            reply: input.reply,
            langs: input.langs,
            selfLabels: input.selfLabels,
            createdAt: this.deps.now(),
        });

        await this.deps.savePost(record);
        return record;
    }

    /**
     * Fetch a single hydrated post view, scoped to `originAppId`. Returns null
     * when the post is missing or owned by a different origin app.
     */
    async getPostView(
        originAppId: string,
        id: string,
        viewerUid: string | null,
    ): Promise<AudioPostView | null> {
        const record = await this.deps.getPostById(originAppId, id);
        if (!record) return null;
        const [view] = await this.hydrateAudioPosts([record], viewerUid);
        return view ?? null;
    }

    /** List the author's posts (origin-app-scoped), hydrated. */
    async getPostsForAuthor(
        originAppId: string,
        authorId: string,
        viewerUid: string | null,
        options?: AudioPostQueryOptions,
    ): Promise<AudioPostView[]> {
        const records = await this.deps.queryByAuthor(originAppId, authorId, options);
        return this.hydrateAudioPosts(records, viewerUid);
    }

    /** List replies to a post (origin-app-scoped), hydrated in thread order. */
    async getReplies(
        originAppId: string,
        parentUri: string,
        viewerUid: string | null,
        options?: AudioPostThreadOptions,
    ): Promise<AudioPostView[]> {
        const records = await this.deps.queryReplies(originAppId, parentUri, options);
        return this.hydrateAudioPosts(records, viewerUid);
    }

    /**
     * Batched hydration (records → views). Loads all authors and transcript
     * enrichments in ONE round each (N+1 ban), then assembles per-record views:
     * lifts the transcript, signs the audio URL, and computes viewer state.
     */
    async hydrateAudioPosts(
        records: AudioPostRecord[],
        viewerUid: string | null,
    ): Promise<AudioPostView[]> {
        if (records.length === 0) return [];

        const authorIds = Array.from(new Set(records.map((r) => r.authorId)));
        const uris = records.map((r) => buildPostUri(r));

        const [authorMap, transcriptMap] = await Promise.all([
            this.deps.getAuthorsByIds(authorIds),
            this.deps.getTranscriptsBySubjectUris(uris),
        ]);

        return Promise.all(
            records.map((record) => this.hydrateOne(record, authorMap, transcriptMap, viewerUid)),
        );
    }

    private async hydrateOne(
        record: AudioPostRecord,
        authorMap: Map<string, ProfileViewBasic>,
        transcriptMap: Map<string, TranscriptEnrichmentRecord>,
        viewerUid: string | null,
    ): Promise<AudioPostView> {
        const uri = buildPostUri(record);

        // --- Hydrated audio embed (signed URL + lifted transcript) ---
        // Guard the nested audio ref defensively: although a parsed record with
        // an `embed` always carries `audio.ref` (schema-enforced), the hydrator
        // is a read boundary that may see records from other code paths.
        const embedRecord = record.embed;
        let embed: AudioEmbedView | undefined;
        if (embedRecord?.audio?.ref) {
            const signedUrl = await this.deps.signAudioUrl(embedRecord.audio.ref);
            if (signedUrl) {
                embed = {
                    $type: 'dev.antiphony.embed.audio#view',
                    url: signedUrl,
                    durationMs: embedRecord.durationMs,
                    alt: embedRecord.alt,
                    waveform: embedRecord.waveform,
                    transcript: transcriptMap.get(uri)?.transcript,
                };
            }
        }

        // Synthetic stub for a missing author so the view still renders, mirroring
        // the legacy reply hydrator's fallback.
        const author: ProfileViewBasic = authorMap.get(record.authorId) ?? {
            id: record.authorId,
            handle: null,
            displayName: 'Unknown User',
        };

        return {
            uri,
            cid: record.id,
            kind: record.kind,
            author,
            record: {
                text: record.text,
                title: record.title,
                reply: record.reply,
                langs: record.langs,
                selfLabels: record.selfLabels,
                createdAt: record.createdAt,
            },
            embed,
            viewer: {
                isAuthor: viewerUid !== null && viewerUid === record.authorId,
            },
        };
    }
}
